// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/youperceive/cloudwego_instance/rpc/order/kitex_gen/base"
)

type QueryOrderIdType int64

const (
	QueryOrderIdType_REQ_USER  QueryOrderIdType = 1
	QueryOrderIdType_RESP_USER QueryOrderIdType = 2
	QueryOrderIdType_EXT_KEY   QueryOrderIdType = 3
)

func (p QueryOrderIdType) String() string {
	switch p {
	case QueryOrderIdType_REQ_USER:
		return "REQ_USER"
	case QueryOrderIdType_RESP_USER:
		return "RESP_USER"
	case QueryOrderIdType_EXT_KEY:
		return "EXT_KEY"
	}
	return "<UNSET>"
}

func QueryOrderIdTypeFromString(s string) (QueryOrderIdType, error) {
	switch s {
	case "REQ_USER":
		return QueryOrderIdType_REQ_USER, nil
	case "RESP_USER":
		return QueryOrderIdType_RESP_USER, nil
	case "EXT_KEY":
		return QueryOrderIdType_EXT_KEY, nil
	}
	return QueryOrderIdType(0), fmt.Errorf("not a valid QueryOrderIdType string")
}

func QueryOrderIdTypePtr(v QueryOrderIdType) *QueryOrderIdType { return &v }
func (p *QueryOrderIdType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = QueryOrderIdType(result.Int64)
	return
}

func (p *QueryOrderIdType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OrderItem struct {
	Id        int64             `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	OrderId   string            `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	ProductId int64             `thrift:"product_id,3" frugal:"3,default,i64" json:"product_id"`
	SkuId     int64             `thrift:"sku_id,4" frugal:"4,default,i64" json:"sku_id"`
	Count     int64             `thrift:"count,5" frugal:"5,default,i64" json:"count"`
	Price     int64             `thrift:"price,6" frugal:"6,default,i64" json:"price"`
	Ext       map[string]string `thrift:"ext,7" frugal:"7,default,map<string:string>" json:"ext"`
}

func NewOrderItem() *OrderItem {
	return &OrderItem{}
}

func (p *OrderItem) InitDefault() {
}

func (p *OrderItem) GetId() (v int64) {
	return p.Id
}

func (p *OrderItem) GetOrderId() (v string) {
	return p.OrderId
}

func (p *OrderItem) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItem) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *OrderItem) GetCount() (v int64) {
	return p.Count
}

func (p *OrderItem) GetPrice() (v int64) {
	return p.Price
}

func (p *OrderItem) GetExt() (v map[string]string) {
	return p.Ext
}
func (p *OrderItem) SetId(val int64) {
	p.Id = val
}
func (p *OrderItem) SetOrderId(val string) {
	p.OrderId = val
}
func (p *OrderItem) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItem) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *OrderItem) SetCount(val int64) {
	p.Count = val
}
func (p *OrderItem) SetPrice(val int64) {
	p.Price = val
}
func (p *OrderItem) SetExt(val map[string]string) {
	p.Ext = val
}

func (p *OrderItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItem(%+v)", *p)
}

var fieldIDToName_OrderItem = map[int16]string{
	1: "id",
	2: "order_id",
	3: "product_id",
	4: "sku_id",
	5: "count",
	6: "price",
	7: "ext",
}

type Order struct {
	Id         string            `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Type       int32             `thrift:"type,2" frugal:"2,default,i32" json:"type"`
	Status     int32             `thrift:"status,3" frugal:"3,default,i32" json:"status"`
	ReqUserId  int64             `thrift:"req_user_id,4" frugal:"4,default,i64" json:"req_user_id"`
	RespUserId int64             `thrift:"resp_user_id,5" frugal:"5,default,i64" json:"resp_user_id"`
	Items      []*OrderItem      `thrift:"items,6" frugal:"6,default,list<OrderItem>" json:"items"`
	CreatedAt  int64             `thrift:"created_at,7" frugal:"7,default,i64" json:"created_at"`
	UpdatedAt  int64             `thrift:"updated_at,8" frugal:"8,default,i64" json:"updated_at"`
	Ext        map[string]string `thrift:"ext,9" frugal:"9,default,map<string:string>" json:"ext"`
}

func NewOrder() *Order {
	return &Order{}
}

func (p *Order) InitDefault() {
}

func (p *Order) GetId() (v string) {
	return p.Id
}

func (p *Order) GetType() (v int32) {
	return p.Type
}

func (p *Order) GetStatus() (v int32) {
	return p.Status
}

func (p *Order) GetReqUserId() (v int64) {
	return p.ReqUserId
}

func (p *Order) GetRespUserId() (v int64) {
	return p.RespUserId
}

func (p *Order) GetItems() (v []*OrderItem) {
	return p.Items
}

func (p *Order) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *Order) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

func (p *Order) GetExt() (v map[string]string) {
	return p.Ext
}
func (p *Order) SetId(val string) {
	p.Id = val
}
func (p *Order) SetType(val int32) {
	p.Type = val
}
func (p *Order) SetStatus(val int32) {
	p.Status = val
}
func (p *Order) SetReqUserId(val int64) {
	p.ReqUserId = val
}
func (p *Order) SetRespUserId(val int64) {
	p.RespUserId = val
}
func (p *Order) SetItems(val []*OrderItem) {
	p.Items = val
}
func (p *Order) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *Order) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *Order) SetExt(val map[string]string) {
	p.Ext = val
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

var fieldIDToName_Order = map[int16]string{
	1: "id",
	2: "type",
	3: "status",
	4: "req_user_id",
	5: "resp_user_id",
	6: "items",
	7: "created_at",
	8: "updated_at",
	9: "ext",
}

type OrderItemForCreate struct {
	ProductId int64             `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
	SkuId     int64             `thrift:"sku_id,2" frugal:"2,default,i64" json:"sku_id"`
	Count     int64             `thrift:"count,3" frugal:"3,default,i64" json:"count"`
	Price     int64             `thrift:"price,4" frugal:"4,default,i64" json:"price"`
	Ext       map[string]string `thrift:"ext,5" frugal:"5,default,map<string:string>" json:"ext"`
}

func NewOrderItemForCreate() *OrderItemForCreate {
	return &OrderItemForCreate{}
}

func (p *OrderItemForCreate) InitDefault() {
}

func (p *OrderItemForCreate) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItemForCreate) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *OrderItemForCreate) GetCount() (v int64) {
	return p.Count
}

func (p *OrderItemForCreate) GetPrice() (v int64) {
	return p.Price
}

func (p *OrderItemForCreate) GetExt() (v map[string]string) {
	return p.Ext
}
func (p *OrderItemForCreate) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItemForCreate) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *OrderItemForCreate) SetCount(val int64) {
	p.Count = val
}
func (p *OrderItemForCreate) SetPrice(val int64) {
	p.Price = val
}
func (p *OrderItemForCreate) SetExt(val map[string]string) {
	p.Ext = val
}

func (p *OrderItemForCreate) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItemForCreate(%+v)", *p)
}

var fieldIDToName_OrderItemForCreate = map[int16]string{
	1: "product_id",
	2: "sku_id",
	3: "count",
	4: "price",
	5: "ext",
}

type CreateRequest struct {
	Type       int32                 `thrift:"type,1" frugal:"1,default,i32" json:"type"`
	Status     int32                 `thrift:"status,2" frugal:"2,default,i32" json:"status"`
	ReqUserId  int64                 `thrift:"req_user_id,3" frugal:"3,default,i64" json:"req_user_id"`
	RespUserId int64                 `thrift:"resp_user_id,4" frugal:"4,default,i64" json:"resp_user_id"`
	Items      []*OrderItemForCreate `thrift:"items,5" frugal:"5,default,list<OrderItemForCreate>" json:"items"`
	Ext        map[string]string     `thrift:"ext,6" frugal:"6,default,map<string:string>" json:"ext"`
}

func NewCreateRequest() *CreateRequest {
	return &CreateRequest{}
}

func (p *CreateRequest) InitDefault() {
}

func (p *CreateRequest) GetType() (v int32) {
	return p.Type
}

func (p *CreateRequest) GetStatus() (v int32) {
	return p.Status
}

func (p *CreateRequest) GetReqUserId() (v int64) {
	return p.ReqUserId
}

func (p *CreateRequest) GetRespUserId() (v int64) {
	return p.RespUserId
}

func (p *CreateRequest) GetItems() (v []*OrderItemForCreate) {
	return p.Items
}

func (p *CreateRequest) GetExt() (v map[string]string) {
	return p.Ext
}
func (p *CreateRequest) SetType(val int32) {
	p.Type = val
}
func (p *CreateRequest) SetStatus(val int32) {
	p.Status = val
}
func (p *CreateRequest) SetReqUserId(val int64) {
	p.ReqUserId = val
}
func (p *CreateRequest) SetRespUserId(val int64) {
	p.RespUserId = val
}
func (p *CreateRequest) SetItems(val []*OrderItemForCreate) {
	p.Items = val
}
func (p *CreateRequest) SetExt(val map[string]string) {
	p.Ext = val
}

func (p *CreateRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateRequest(%+v)", *p)
}

var fieldIDToName_CreateRequest = map[int16]string{
	1: "type",
	2: "status",
	3: "req_user_id",
	4: "resp_user_id",
	5: "items",
	6: "ext",
}

type CreateResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	OrderId  string             `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
}

func NewCreateResponse() *CreateResponse {
	return &CreateResponse{}
}

func (p *CreateResponse) InitDefault() {
}

var CreateResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *CreateResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return CreateResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CreateResponse) GetOrderId() (v string) {
	return p.OrderId
}
func (p *CreateResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *CreateResponse) SetOrderId(val string) {
	p.OrderId = val
}

func (p *CreateResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateResponse(%+v)", *p)
}

var fieldIDToName_CreateResponse = map[int16]string{
	1: "baseResp",
	2: "order_id",
}

type UpdateRequest struct {
	Id     string            `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Status *int32            `thrift:"status,2,optional" frugal:"2,optional,i32" json:"status,omitempty"`
	Ext    map[string]string `thrift:"ext,3,optional" frugal:"3,optional,map<string:string>" json:"ext,omitempty"`
}

func NewUpdateRequest() *UpdateRequest {
	return &UpdateRequest{}
}

func (p *UpdateRequest) InitDefault() {
}

func (p *UpdateRequest) GetId() (v string) {
	return p.Id
}

var UpdateRequest_Status_DEFAULT int32

func (p *UpdateRequest) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return UpdateRequest_Status_DEFAULT
	}
	return *p.Status
}

var UpdateRequest_Ext_DEFAULT map[string]string

func (p *UpdateRequest) GetExt() (v map[string]string) {
	if !p.IsSetExt() {
		return UpdateRequest_Ext_DEFAULT
	}
	return p.Ext
}
func (p *UpdateRequest) SetId(val string) {
	p.Id = val
}
func (p *UpdateRequest) SetStatus(val *int32) {
	p.Status = val
}
func (p *UpdateRequest) SetExt(val map[string]string) {
	p.Ext = val
}

func (p *UpdateRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *UpdateRequest) IsSetExt() bool {
	return p.Ext != nil
}

func (p *UpdateRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRequest(%+v)", *p)
}

var fieldIDToName_UpdateRequest = map[int16]string{
	1: "id",
	2: "status",
	3: "ext",
}

type UpdateResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
}

func NewUpdateResponse() *UpdateResponse {
	return &UpdateResponse{}
}

func (p *UpdateResponse) InitDefault() {
}

var UpdateResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *UpdateResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return UpdateResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *UpdateResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateResponse(%+v)", *p)
}

var fieldIDToName_UpdateResponse = map[int16]string{
	1: "baseResp",
}

type QueryOrderInfoRequest struct {
	Id string `thrift:"id,1" frugal:"1,default,string" json:"id"`
}

func NewQueryOrderInfoRequest() *QueryOrderInfoRequest {
	return &QueryOrderInfoRequest{}
}

func (p *QueryOrderInfoRequest) InitDefault() {
}

func (p *QueryOrderInfoRequest) GetId() (v string) {
	return p.Id
}
func (p *QueryOrderInfoRequest) SetId(val string) {
	p.Id = val
}

func (p *QueryOrderInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderInfoRequest(%+v)", *p)
}

var fieldIDToName_QueryOrderInfoRequest = map[int16]string{
	1: "id",
}

type QueryOrderInfoResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	Order    *Order             `thrift:"order,2" frugal:"2,default,Order" json:"order"`
}

func NewQueryOrderInfoResponse() *QueryOrderInfoResponse {
	return &QueryOrderInfoResponse{}
}

func (p *QueryOrderInfoResponse) InitDefault() {
}

var QueryOrderInfoResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *QueryOrderInfoResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return QueryOrderInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var QueryOrderInfoResponse_Order_DEFAULT *Order

func (p *QueryOrderInfoResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return QueryOrderInfoResponse_Order_DEFAULT
	}
	return p.Order
}
func (p *QueryOrderInfoResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *QueryOrderInfoResponse) SetOrder(val *Order) {
	p.Order = val
}

func (p *QueryOrderInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *QueryOrderInfoResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *QueryOrderInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderInfoResponse(%+v)", *p)
}

var fieldIDToName_QueryOrderInfoResponse = map[int16]string{
	1: "baseResp",
	2: "order",
}

type QueryOrderIdRequest struct {
	Type     QueryOrderIdType `thrift:"type,1" frugal:"1,default,QueryOrderIdType" json:"type"`
	UserId   *int64           `thrift:"user_id,2,optional" frugal:"2,optional,i64" json:"user_id,omitempty"`
	ExtKey   *string          `thrift:"ext_key,3,optional" frugal:"3,optional,string" json:"ext_key,omitempty"`
	ExtVal   *string          `thrift:"ext_val,4,optional" frugal:"4,optional,string" json:"ext_val,omitempty"`
	Page     int32            `thrift:"page,5,optional" frugal:"5,optional,i32" json:"page,omitempty"`
	PageSize int32            `thrift:"page_size,6,optional" frugal:"6,optional,i32" json:"page_size,omitempty"`
}

func NewQueryOrderIdRequest() *QueryOrderIdRequest {
	return &QueryOrderIdRequest{
		Page:     1,
		PageSize: 20,
	}
}

func (p *QueryOrderIdRequest) InitDefault() {
	p.Page = 1
	p.PageSize = 20
}

func (p *QueryOrderIdRequest) GetType() (v QueryOrderIdType) {
	return p.Type
}

var QueryOrderIdRequest_UserId_DEFAULT int64

func (p *QueryOrderIdRequest) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return QueryOrderIdRequest_UserId_DEFAULT
	}
	return *p.UserId
}

var QueryOrderIdRequest_ExtKey_DEFAULT string

func (p *QueryOrderIdRequest) GetExtKey() (v string) {
	if !p.IsSetExtKey() {
		return QueryOrderIdRequest_ExtKey_DEFAULT
	}
	return *p.ExtKey
}

var QueryOrderIdRequest_ExtVal_DEFAULT string

func (p *QueryOrderIdRequest) GetExtVal() (v string) {
	if !p.IsSetExtVal() {
		return QueryOrderIdRequest_ExtVal_DEFAULT
	}
	return *p.ExtVal
}

var QueryOrderIdRequest_Page_DEFAULT int32 = 1

func (p *QueryOrderIdRequest) GetPage() (v int32) {
	if !p.IsSetPage() {
		return QueryOrderIdRequest_Page_DEFAULT
	}
	return p.Page
}

var QueryOrderIdRequest_PageSize_DEFAULT int32 = 20

func (p *QueryOrderIdRequest) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return QueryOrderIdRequest_PageSize_DEFAULT
	}
	return p.PageSize
}
func (p *QueryOrderIdRequest) SetType(val QueryOrderIdType) {
	p.Type = val
}
func (p *QueryOrderIdRequest) SetUserId(val *int64) {
	p.UserId = val
}
func (p *QueryOrderIdRequest) SetExtKey(val *string) {
	p.ExtKey = val
}
func (p *QueryOrderIdRequest) SetExtVal(val *string) {
	p.ExtVal = val
}
func (p *QueryOrderIdRequest) SetPage(val int32) {
	p.Page = val
}
func (p *QueryOrderIdRequest) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *QueryOrderIdRequest) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *QueryOrderIdRequest) IsSetExtKey() bool {
	return p.ExtKey != nil
}

func (p *QueryOrderIdRequest) IsSetExtVal() bool {
	return p.ExtVal != nil
}

func (p *QueryOrderIdRequest) IsSetPage() bool {
	return p.Page != QueryOrderIdRequest_Page_DEFAULT
}

func (p *QueryOrderIdRequest) IsSetPageSize() bool {
	return p.PageSize != QueryOrderIdRequest_PageSize_DEFAULT
}

func (p *QueryOrderIdRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderIdRequest(%+v)", *p)
}

var fieldIDToName_QueryOrderIdRequest = map[int16]string{
	1: "type",
	2: "user_id",
	3: "ext_key",
	4: "ext_val",
	5: "page",
	6: "page_size",
}

type QueryOrderIdResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	OrderId  []string           `thrift:"order_id,2" frugal:"2,default,list<string>" json:"order_id"`
	Total    int32              `thrift:"total,3" frugal:"3,default,i32" json:"total"`
	Page     int32              `thrift:"page,4" frugal:"4,default,i32" json:"page"`
	PageSize int32              `thrift:"page_size,5" frugal:"5,default,i32" json:"page_size"`
}

func NewQueryOrderIdResponse() *QueryOrderIdResponse {
	return &QueryOrderIdResponse{}
}

func (p *QueryOrderIdResponse) InitDefault() {
}

var QueryOrderIdResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *QueryOrderIdResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return QueryOrderIdResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *QueryOrderIdResponse) GetOrderId() (v []string) {
	return p.OrderId
}

func (p *QueryOrderIdResponse) GetTotal() (v int32) {
	return p.Total
}

func (p *QueryOrderIdResponse) GetPage() (v int32) {
	return p.Page
}

func (p *QueryOrderIdResponse) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *QueryOrderIdResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *QueryOrderIdResponse) SetOrderId(val []string) {
	p.OrderId = val
}
func (p *QueryOrderIdResponse) SetTotal(val int32) {
	p.Total = val
}
func (p *QueryOrderIdResponse) SetPage(val int32) {
	p.Page = val
}
func (p *QueryOrderIdResponse) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *QueryOrderIdResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *QueryOrderIdResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderIdResponse(%+v)", *p)
}

var fieldIDToName_QueryOrderIdResponse = map[int16]string{
	1: "baseResp",
	2: "order_id",
	3: "total",
	4: "page",
	5: "page_size",
}

type OrderService interface {
	Create(ctx context.Context, req *CreateRequest) (r *CreateResponse, err error)

	Update(ctx context.Context, req *UpdateRequest) (r *UpdateResponse, err error)

	QueryOrderInfo(ctx context.Context, req *QueryOrderInfoRequest) (r *QueryOrderInfoResponse, err error)

	QueryOrderId(ctx context.Context, req *QueryOrderIdRequest) (r *QueryOrderIdResponse, err error)
}

type OrderServiceCreateArgs struct {
	Req *CreateRequest `thrift:"req,1" frugal:"1,default,CreateRequest" json:"req"`
}

func NewOrderServiceCreateArgs() *OrderServiceCreateArgs {
	return &OrderServiceCreateArgs{}
}

func (p *OrderServiceCreateArgs) InitDefault() {
}

var OrderServiceCreateArgs_Req_DEFAULT *CreateRequest

func (p *OrderServiceCreateArgs) GetReq() (v *CreateRequest) {
	if !p.IsSetReq() {
		return OrderServiceCreateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateArgs) SetReq(val *CreateRequest) {
	p.Req = val
}

func (p *OrderServiceCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateResult struct {
	Success *CreateResponse `thrift:"success,0,optional" frugal:"0,optional,CreateResponse" json:"success,omitempty"`
}

func NewOrderServiceCreateResult() *OrderServiceCreateResult {
	return &OrderServiceCreateResult{}
}

func (p *OrderServiceCreateResult) InitDefault() {
}

var OrderServiceCreateResult_Success_DEFAULT *CreateResponse

func (p *OrderServiceCreateResult) GetSuccess() (v *CreateResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateResponse)
}

func (p *OrderServiceCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateResult = map[int16]string{
	0: "success",
}

type OrderServiceUpdateArgs struct {
	Req *UpdateRequest `thrift:"req,1" frugal:"1,default,UpdateRequest" json:"req"`
}

func NewOrderServiceUpdateArgs() *OrderServiceUpdateArgs {
	return &OrderServiceUpdateArgs{}
}

func (p *OrderServiceUpdateArgs) InitDefault() {
}

var OrderServiceUpdateArgs_Req_DEFAULT *UpdateRequest

func (p *OrderServiceUpdateArgs) GetReq() (v *UpdateRequest) {
	if !p.IsSetReq() {
		return OrderServiceUpdateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceUpdateArgs) SetReq(val *UpdateRequest) {
	p.Req = val
}

func (p *OrderServiceUpdateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceUpdateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateArgs = map[int16]string{
	1: "req",
}

type OrderServiceUpdateResult struct {
	Success *UpdateResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateResponse" json:"success,omitempty"`
}

func NewOrderServiceUpdateResult() *OrderServiceUpdateResult {
	return &OrderServiceUpdateResult{}
}

func (p *OrderServiceUpdateResult) InitDefault() {
}

var OrderServiceUpdateResult_Success_DEFAULT *UpdateResponse

func (p *OrderServiceUpdateResult) GetSuccess() (v *UpdateResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceUpdateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceUpdateResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateResponse)
}

func (p *OrderServiceUpdateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceUpdateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateResult(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateResult = map[int16]string{
	0: "success",
}

type OrderServiceQueryOrderInfoArgs struct {
	Req *QueryOrderInfoRequest `thrift:"req,1" frugal:"1,default,QueryOrderInfoRequest" json:"req"`
}

func NewOrderServiceQueryOrderInfoArgs() *OrderServiceQueryOrderInfoArgs {
	return &OrderServiceQueryOrderInfoArgs{}
}

func (p *OrderServiceQueryOrderInfoArgs) InitDefault() {
}

var OrderServiceQueryOrderInfoArgs_Req_DEFAULT *QueryOrderInfoRequest

func (p *OrderServiceQueryOrderInfoArgs) GetReq() (v *QueryOrderInfoRequest) {
	if !p.IsSetReq() {
		return OrderServiceQueryOrderInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceQueryOrderInfoArgs) SetReq(val *QueryOrderInfoRequest) {
	p.Req = val
}

func (p *OrderServiceQueryOrderInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceQueryOrderInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrderInfoArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrderInfoArgs = map[int16]string{
	1: "req",
}

type OrderServiceQueryOrderInfoResult struct {
	Success *QueryOrderInfoResponse `thrift:"success,0,optional" frugal:"0,optional,QueryOrderInfoResponse" json:"success,omitempty"`
}

func NewOrderServiceQueryOrderInfoResult() *OrderServiceQueryOrderInfoResult {
	return &OrderServiceQueryOrderInfoResult{}
}

func (p *OrderServiceQueryOrderInfoResult) InitDefault() {
}

var OrderServiceQueryOrderInfoResult_Success_DEFAULT *QueryOrderInfoResponse

func (p *OrderServiceQueryOrderInfoResult) GetSuccess() (v *QueryOrderInfoResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceQueryOrderInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceQueryOrderInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryOrderInfoResponse)
}

func (p *OrderServiceQueryOrderInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceQueryOrderInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrderInfoResult(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrderInfoResult = map[int16]string{
	0: "success",
}

type OrderServiceQueryOrderIdArgs struct {
	Req *QueryOrderIdRequest `thrift:"req,1" frugal:"1,default,QueryOrderIdRequest" json:"req"`
}

func NewOrderServiceQueryOrderIdArgs() *OrderServiceQueryOrderIdArgs {
	return &OrderServiceQueryOrderIdArgs{}
}

func (p *OrderServiceQueryOrderIdArgs) InitDefault() {
}

var OrderServiceQueryOrderIdArgs_Req_DEFAULT *QueryOrderIdRequest

func (p *OrderServiceQueryOrderIdArgs) GetReq() (v *QueryOrderIdRequest) {
	if !p.IsSetReq() {
		return OrderServiceQueryOrderIdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceQueryOrderIdArgs) SetReq(val *QueryOrderIdRequest) {
	p.Req = val
}

func (p *OrderServiceQueryOrderIdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceQueryOrderIdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrderIdArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrderIdArgs = map[int16]string{
	1: "req",
}

type OrderServiceQueryOrderIdResult struct {
	Success *QueryOrderIdResponse `thrift:"success,0,optional" frugal:"0,optional,QueryOrderIdResponse" json:"success,omitempty"`
}

func NewOrderServiceQueryOrderIdResult() *OrderServiceQueryOrderIdResult {
	return &OrderServiceQueryOrderIdResult{}
}

func (p *OrderServiceQueryOrderIdResult) InitDefault() {
}

var OrderServiceQueryOrderIdResult_Success_DEFAULT *QueryOrderIdResponse

func (p *OrderServiceQueryOrderIdResult) GetSuccess() (v *QueryOrderIdResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceQueryOrderIdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceQueryOrderIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryOrderIdResponse)
}

func (p *OrderServiceQueryOrderIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceQueryOrderIdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrderIdResult(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrderIdResult = map[int16]string{
	0: "success",
}
