// Code generated by hertz generator.

package verify_code

import "github.com/cloudwego/hertz/pkg/app"

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verify_codeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generatecaptchaMw() []app.HandlerFunc {
	// your code...
	return nil
}
