// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deductskustockMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmerchantMw() []app.HandlerFunc {
	// your code...
	return nil
}
