// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user_account

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/youperceive/cloudwego_instance/rpc/user_account/kitex_gen/base"
)

type UserType int64

const (
	UserType_USER        UserType = 1
	UserType_ADMIN       UserType = 2
	UserType_THIRD_PARTY UserType = 3
)

func (p UserType) String() string {
	switch p {
	case UserType_USER:
		return "USER"
	case UserType_ADMIN:
		return "ADMIN"
	case UserType_THIRD_PARTY:
		return "THIRD_PARTY"
	}
	return "<UNSET>"
}

func UserTypeFromString(s string) (UserType, error) {
	switch s {
	case "USER":
		return UserType_USER, nil
	case "ADMIN":
		return UserType_ADMIN, nil
	case "THIRD_PARTY":
		return UserType_THIRD_PARTY, nil
	}
	return UserType(0), fmt.Errorf("not a valid UserType string")
}

func UserTypePtr(v UserType) *UserType { return &v }
func (p *UserType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = UserType(result.Int64)
	return
}

func (p *UserType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type User struct {
	Id        int64             `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username  string            `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Email     string            `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Phone     string            `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	Ext       map[string]string `thrift:"ext,5,optional" frugal:"5,optional,map<string:string>" json:"ext,omitempty"`
	UserType  UserType          `thrift:"user_type,6,optional" frugal:"6,optional,UserType" json:"user_type,omitempty"`
	CreatedAt *int64            `thrift:"created_at,7,optional" frugal:"7,optional,i64" json:"created_at,omitempty"`
	UpdatedAt *int64            `thrift:"updated_at,8,optional" frugal:"8,optional,i64" json:"updated_at,omitempty"`
	Status    int32             `thrift:"status,9,optional" frugal:"9,optional,i32" json:"status,omitempty"`
}

func NewUser() *User {
	return &User{
		Ext:      map[string]string{},
		UserType: UserType_USER,
		Status:   1,
	}
}

func (p *User) InitDefault() {
	p.Ext = map[string]string{}
	p.UserType = UserType_USER
	p.Status = 1
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

var User_Ext_DEFAULT map[string]string = map[string]string{}

func (p *User) GetExt() (v map[string]string) {
	if !p.IsSetExt() {
		return User_Ext_DEFAULT
	}
	return p.Ext
}

var User_UserType_DEFAULT UserType = UserType_USER

func (p *User) GetUserType() (v UserType) {
	if !p.IsSetUserType() {
		return User_UserType_DEFAULT
	}
	return p.UserType
}

var User_CreatedAt_DEFAULT int64

func (p *User) GetCreatedAt() (v int64) {
	if !p.IsSetCreatedAt() {
		return User_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var User_UpdatedAt_DEFAULT int64

func (p *User) GetUpdatedAt() (v int64) {
	if !p.IsSetUpdatedAt() {
		return User_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

var User_Status_DEFAULT int32 = 1

func (p *User) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return User_Status_DEFAULT
	}
	return p.Status
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetExt(val map[string]string) {
	p.Ext = val
}
func (p *User) SetUserType(val UserType) {
	p.UserType = val
}
func (p *User) SetCreatedAt(val *int64) {
	p.CreatedAt = val
}
func (p *User) SetUpdatedAt(val *int64) {
	p.UpdatedAt = val
}
func (p *User) SetStatus(val int32) {
	p.Status = val
}

func (p *User) IsSetExt() bool {
	return p.Ext != nil
}

func (p *User) IsSetUserType() bool {
	return p.UserType != User_UserType_DEFAULT
}

func (p *User) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *User) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *User) IsSetStatus() bool {
	return p.Status != User_Status_DEFAULT
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "username",
	3: "email",
	4: "phone",
	5: "ext",
	6: "user_type",
	7: "created_at",
	8: "updated_at",
	9: "status",
}

type RegisterRequest struct {
	Username   *string         `thrift:"username,1,optional" frugal:"1,optional,string" json:"username,omitempty"`
	Target     string          `thrift:"target,2" frugal:"2,default,string" json:"target"`
	TargetType base.TargetType `thrift:"target_type,3" frugal:"3,default,TargetType" json:"target_type"`
	Password   string          `thrift:"password,4" frugal:"4,default,string" json:"password"`
	Captcha    string          `thrift:"captcha,5" frugal:"5,default,string" json:"captcha"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

var RegisterRequest_Username_DEFAULT string

func (p *RegisterRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return RegisterRequest_Username_DEFAULT
	}
	return *p.Username
}

func (p *RegisterRequest) GetTarget() (v string) {
	return p.Target
}

func (p *RegisterRequest) GetTargetType() (v base.TargetType) {
	return p.TargetType
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterRequest) GetCaptcha() (v string) {
	return p.Captcha
}
func (p *RegisterRequest) SetUsername(val *string) {
	p.Username = val
}
func (p *RegisterRequest) SetTarget(val string) {
	p.Target = val
}
func (p *RegisterRequest) SetTargetType(val base.TargetType) {
	p.TargetType = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterRequest) SetCaptcha(val string) {
	p.Captcha = val
}

func (p *RegisterRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "username",
	2: "target",
	3: "target_type",
	4: "password",
	5: "captcha",
}

type RegisterResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	UserId   *int64             `thrift:"user_id,2,optional" frugal:"2,optional,i64" json:"user_id,omitempty"`
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

var RegisterResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *RegisterResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return RegisterResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var RegisterResponse_UserId_DEFAULT int64

func (p *RegisterResponse) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return RegisterResponse_UserId_DEFAULT
	}
	return *p.UserId
}
func (p *RegisterResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *RegisterResponse) SetUserId(val *int64) {
	p.UserId = val
}

func (p *RegisterResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RegisterResponse) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

var fieldIDToName_RegisterResponse = map[int16]string{
	1: "baseResp",
	2: "user_id",
}

type LoginRequest struct {
	Target     string          `thrift:"target,1" frugal:"1,default,string" json:"target"`
	TargetType base.TargetType `thrift:"target_type,2" frugal:"2,default,TargetType" json:"target_type"`
	Password   string          `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetTarget() (v string) {
	return p.Target
}

func (p *LoginRequest) GetTargetType() (v base.TargetType) {
	return p.TargetType
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *LoginRequest) SetTarget(val string) {
	p.Target = val
}
func (p *LoginRequest) SetTargetType(val base.TargetType) {
	p.TargetType = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "target",
	2: "target_type",
	3: "password",
}

type LoginResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	Token    string             `thrift:"token,2" frugal:"2,default,string" json:"token"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

var LoginResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *LoginResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return LoginResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *LoginResponse) GetToken() (v string) {
	return p.Token
}
func (p *LoginResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *LoginResponse) SetToken(val string) {
	p.Token = val
}

func (p *LoginResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "baseResp",
	2: "token",
}

type UserAccountService interface {
	Register(ctx context.Context, req *RegisterRequest) (r *RegisterResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)
}

type UserAccountServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewUserAccountServiceRegisterArgs() *UserAccountServiceRegisterArgs {
	return &UserAccountServiceRegisterArgs{}
}

func (p *UserAccountServiceRegisterArgs) InitDefault() {
}

var UserAccountServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *UserAccountServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return UserAccountServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserAccountServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *UserAccountServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserAccountServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserAccountServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserAccountServiceRegisterResult struct {
	Success *RegisterResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterResponse" json:"success,omitempty"`
}

func NewUserAccountServiceRegisterResult() *UserAccountServiceRegisterResult {
	return &UserAccountServiceRegisterResult{}
}

func (p *UserAccountServiceRegisterResult) InitDefault() {
}

var UserAccountServiceRegisterResult_Success_DEFAULT *RegisterResponse

func (p *UserAccountServiceRegisterResult) GetSuccess() (v *RegisterResponse) {
	if !p.IsSetSuccess() {
		return UserAccountServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserAccountServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResponse)
}

func (p *UserAccountServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserAccountServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserAccountServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserAccountServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserAccountServiceLoginArgs() *UserAccountServiceLoginArgs {
	return &UserAccountServiceLoginArgs{}
}

func (p *UserAccountServiceLoginArgs) InitDefault() {
}

var UserAccountServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *UserAccountServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserAccountServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserAccountServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserAccountServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserAccountServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserAccountServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserAccountServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserAccountServiceLoginResult() *UserAccountServiceLoginResult {
	return &UserAccountServiceLoginResult{}
}

func (p *UserAccountServiceLoginResult) InitDefault() {
}

var UserAccountServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserAccountServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserAccountServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserAccountServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserAccountServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserAccountServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserAccountServiceLoginResult = map[int16]string{
	0: "success",
}
