// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user_account

import (
	"context"
	"fmt"
	"github.com/youperceive/cloudwego_instance/rpc/user_account/kitex_gen/base"
)

type User struct {
	Id        int64             `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username  string            `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Email     string            `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Phone     string            `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	Ext       map[string]string `thrift:"ext,5,optional" frugal:"5,optional,map<string:string>" json:"ext,omitempty"`
	UserType  int8              `thrift:"user_type,6,optional" frugal:"6,optional,i8" json:"user_type,omitempty"`
	CreatedAt *int64            `thrift:"created_at,7,optional" frugal:"7,optional,i64" json:"created_at,omitempty"`
	UpdatedAt *int64            `thrift:"updated_at,8,optional" frugal:"8,optional,i64" json:"updated_at,omitempty"`
	Status    int32             `thrift:"status,9,optional" frugal:"9,optional,i32" json:"status,omitempty"`
}

func NewUser() *User {
	return &User{
		Ext:      map[string]string{},
		UserType: 1,
		Status:   1,
	}
}

func (p *User) InitDefault() {
	p.Ext = map[string]string{}
	p.UserType = 1
	p.Status = 1
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

var User_Ext_DEFAULT map[string]string = map[string]string{}

func (p *User) GetExt() (v map[string]string) {
	if !p.IsSetExt() {
		return User_Ext_DEFAULT
	}
	return p.Ext
}

var User_UserType_DEFAULT int8 = 1

func (p *User) GetUserType() (v int8) {
	if !p.IsSetUserType() {
		return User_UserType_DEFAULT
	}
	return p.UserType
}

var User_CreatedAt_DEFAULT int64

func (p *User) GetCreatedAt() (v int64) {
	if !p.IsSetCreatedAt() {
		return User_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var User_UpdatedAt_DEFAULT int64

func (p *User) GetUpdatedAt() (v int64) {
	if !p.IsSetUpdatedAt() {
		return User_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

var User_Status_DEFAULT int32 = 1

func (p *User) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return User_Status_DEFAULT
	}
	return p.Status
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetExt(val map[string]string) {
	p.Ext = val
}
func (p *User) SetUserType(val int8) {
	p.UserType = val
}
func (p *User) SetCreatedAt(val *int64) {
	p.CreatedAt = val
}
func (p *User) SetUpdatedAt(val *int64) {
	p.UpdatedAt = val
}
func (p *User) SetStatus(val int32) {
	p.Status = val
}

func (p *User) IsSetExt() bool {
	return p.Ext != nil
}

func (p *User) IsSetUserType() bool {
	return p.UserType != User_UserType_DEFAULT
}

func (p *User) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *User) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *User) IsSetStatus() bool {
	return p.Status != User_Status_DEFAULT
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "username",
	3: "email",
	4: "phone",
	5: "ext",
	6: "user_type",
	7: "created_at",
	8: "updated_at",
	9: "status",
}

type RegisterRequest struct {
	Username   *string         `thrift:"username,1,optional" frugal:"1,optional,string" json:"username,omitempty"`
	Target     string          `thrift:"target,2" frugal:"2,default,string" json:"target"`
	TargetType base.TargetType `thrift:"target_type,3" frugal:"3,default,TargetType" json:"target_type"`
	Password   string          `thrift:"password,4" frugal:"4,default,string" json:"password"`
	Captcha    string          `thrift:"captcha,5" frugal:"5,default,string" json:"captcha"`
	UserType   int8            `thrift:"user_type,6,optional" frugal:"6,optional,i8" json:"user_type,omitempty"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{
		UserType: 1,
	}
}

func (p *RegisterRequest) InitDefault() {
	p.UserType = 1
}

var RegisterRequest_Username_DEFAULT string

func (p *RegisterRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return RegisterRequest_Username_DEFAULT
	}
	return *p.Username
}

func (p *RegisterRequest) GetTarget() (v string) {
	return p.Target
}

func (p *RegisterRequest) GetTargetType() (v base.TargetType) {
	return p.TargetType
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterRequest) GetCaptcha() (v string) {
	return p.Captcha
}

var RegisterRequest_UserType_DEFAULT int8 = 1

func (p *RegisterRequest) GetUserType() (v int8) {
	if !p.IsSetUserType() {
		return RegisterRequest_UserType_DEFAULT
	}
	return p.UserType
}
func (p *RegisterRequest) SetUsername(val *string) {
	p.Username = val
}
func (p *RegisterRequest) SetTarget(val string) {
	p.Target = val
}
func (p *RegisterRequest) SetTargetType(val base.TargetType) {
	p.TargetType = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterRequest) SetCaptcha(val string) {
	p.Captcha = val
}
func (p *RegisterRequest) SetUserType(val int8) {
	p.UserType = val
}

func (p *RegisterRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *RegisterRequest) IsSetUserType() bool {
	return p.UserType != RegisterRequest_UserType_DEFAULT
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "username",
	2: "target",
	3: "target_type",
	4: "password",
	5: "captcha",
	6: "user_type",
}

type RegisterResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	UserId   *int64             `thrift:"user_id,2,optional" frugal:"2,optional,i64" json:"user_id,omitempty"`
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

var RegisterResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *RegisterResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return RegisterResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var RegisterResponse_UserId_DEFAULT int64

func (p *RegisterResponse) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return RegisterResponse_UserId_DEFAULT
	}
	return *p.UserId
}
func (p *RegisterResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *RegisterResponse) SetUserId(val *int64) {
	p.UserId = val
}

func (p *RegisterResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RegisterResponse) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

var fieldIDToName_RegisterResponse = map[int16]string{
	1: "baseResp",
	2: "user_id",
}

type LoginRequest struct {
	Target     string          `thrift:"target,1" frugal:"1,default,string" json:"target"`
	TargetType base.TargetType `thrift:"target_type,2" frugal:"2,default,TargetType" json:"target_type"`
	Password   string          `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetTarget() (v string) {
	return p.Target
}

func (p *LoginRequest) GetTargetType() (v base.TargetType) {
	return p.TargetType
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *LoginRequest) SetTarget(val string) {
	p.Target = val
}
func (p *LoginRequest) SetTargetType(val base.TargetType) {
	p.TargetType = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "target",
	2: "target_type",
	3: "password",
}

type LoginResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	Token    string             `thrift:"token,2" frugal:"2,default,string" json:"token"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

var LoginResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *LoginResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return LoginResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *LoginResponse) GetToken() (v string) {
	return p.Token
}
func (p *LoginResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *LoginResponse) SetToken(val string) {
	p.Token = val
}

func (p *LoginResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "baseResp",
	2: "token",
}

type UpdateRequest struct {
	Id       *int64  `thrift:"id,1,optional" frugal:"1,optional,i64" json:"id,omitempty"`
	Username *string `thrift:"username,2,optional" frugal:"2,optional,string" json:"username,omitempty"`
	Email    *string `thrift:"email,3,optional" frugal:"3,optional,string" json:"email,omitempty"`
	Phone    *string `thrift:"phone,4,optional" frugal:"4,optional,string" json:"phone,omitempty"`
	Password *string `thrift:"password,5,optional" frugal:"5,optional,string" json:"password,omitempty"`
	UserType *int8   `thrift:"user_type,6,optional" frugal:"6,optional,i8" json:"user_type,omitempty"`
	Status   *int32  `thrift:"status,7,optional" frugal:"7,optional,i32" json:"status,omitempty"`
}

func NewUpdateRequest() *UpdateRequest {
	return &UpdateRequest{}
}

func (p *UpdateRequest) InitDefault() {
}

var UpdateRequest_Id_DEFAULT int64

func (p *UpdateRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return UpdateRequest_Id_DEFAULT
	}
	return *p.Id
}

var UpdateRequest_Username_DEFAULT string

func (p *UpdateRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UpdateRequest_Username_DEFAULT
	}
	return *p.Username
}

var UpdateRequest_Email_DEFAULT string

func (p *UpdateRequest) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return UpdateRequest_Email_DEFAULT
	}
	return *p.Email
}

var UpdateRequest_Phone_DEFAULT string

func (p *UpdateRequest) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return UpdateRequest_Phone_DEFAULT
	}
	return *p.Phone
}

var UpdateRequest_Password_DEFAULT string

func (p *UpdateRequest) GetPassword() (v string) {
	if !p.IsSetPassword() {
		return UpdateRequest_Password_DEFAULT
	}
	return *p.Password
}

var UpdateRequest_UserType_DEFAULT int8

func (p *UpdateRequest) GetUserType() (v int8) {
	if !p.IsSetUserType() {
		return UpdateRequest_UserType_DEFAULT
	}
	return *p.UserType
}

var UpdateRequest_Status_DEFAULT int32

func (p *UpdateRequest) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return UpdateRequest_Status_DEFAULT
	}
	return *p.Status
}
func (p *UpdateRequest) SetId(val *int64) {
	p.Id = val
}
func (p *UpdateRequest) SetUsername(val *string) {
	p.Username = val
}
func (p *UpdateRequest) SetEmail(val *string) {
	p.Email = val
}
func (p *UpdateRequest) SetPhone(val *string) {
	p.Phone = val
}
func (p *UpdateRequest) SetPassword(val *string) {
	p.Password = val
}
func (p *UpdateRequest) SetUserType(val *int8) {
	p.UserType = val
}
func (p *UpdateRequest) SetStatus(val *int32) {
	p.Status = val
}

func (p *UpdateRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *UpdateRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UpdateRequest) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UpdateRequest) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UpdateRequest) IsSetPassword() bool {
	return p.Password != nil
}

func (p *UpdateRequest) IsSetUserType() bool {
	return p.UserType != nil
}

func (p *UpdateRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *UpdateRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRequest(%+v)", *p)
}

var fieldIDToName_UpdateRequest = map[int16]string{
	1: "id",
	2: "username",
	3: "email",
	4: "phone",
	5: "password",
	6: "user_type",
	7: "status",
}

type UpdateResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
}

func NewUpdateResponse() *UpdateResponse {
	return &UpdateResponse{}
}

func (p *UpdateResponse) InitDefault() {
}

var UpdateResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *UpdateResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return UpdateResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *UpdateResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateResponse(%+v)", *p)
}

var fieldIDToName_UpdateResponse = map[int16]string{
	1: "baseResp",
}

type UserAccountService interface {
	Register(ctx context.Context, req *RegisterRequest) (r *RegisterResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	Update(ctx context.Context, req *UpdateRequest) (r *UpdateResponse, err error)
}

type UserAccountServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewUserAccountServiceRegisterArgs() *UserAccountServiceRegisterArgs {
	return &UserAccountServiceRegisterArgs{}
}

func (p *UserAccountServiceRegisterArgs) InitDefault() {
}

var UserAccountServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *UserAccountServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return UserAccountServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserAccountServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *UserAccountServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserAccountServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserAccountServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserAccountServiceRegisterResult struct {
	Success *RegisterResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterResponse" json:"success,omitempty"`
}

func NewUserAccountServiceRegisterResult() *UserAccountServiceRegisterResult {
	return &UserAccountServiceRegisterResult{}
}

func (p *UserAccountServiceRegisterResult) InitDefault() {
}

var UserAccountServiceRegisterResult_Success_DEFAULT *RegisterResponse

func (p *UserAccountServiceRegisterResult) GetSuccess() (v *RegisterResponse) {
	if !p.IsSetSuccess() {
		return UserAccountServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserAccountServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResponse)
}

func (p *UserAccountServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserAccountServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserAccountServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserAccountServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserAccountServiceLoginArgs() *UserAccountServiceLoginArgs {
	return &UserAccountServiceLoginArgs{}
}

func (p *UserAccountServiceLoginArgs) InitDefault() {
}

var UserAccountServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *UserAccountServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserAccountServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserAccountServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserAccountServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserAccountServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserAccountServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserAccountServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserAccountServiceLoginResult() *UserAccountServiceLoginResult {
	return &UserAccountServiceLoginResult{}
}

func (p *UserAccountServiceLoginResult) InitDefault() {
}

var UserAccountServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserAccountServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserAccountServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserAccountServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserAccountServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserAccountServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserAccountServiceLoginResult = map[int16]string{
	0: "success",
}

type UserAccountServiceUpdateArgs struct {
	Req *UpdateRequest `thrift:"req,1" frugal:"1,default,UpdateRequest" json:"req"`
}

func NewUserAccountServiceUpdateArgs() *UserAccountServiceUpdateArgs {
	return &UserAccountServiceUpdateArgs{}
}

func (p *UserAccountServiceUpdateArgs) InitDefault() {
}

var UserAccountServiceUpdateArgs_Req_DEFAULT *UpdateRequest

func (p *UserAccountServiceUpdateArgs) GetReq() (v *UpdateRequest) {
	if !p.IsSetReq() {
		return UserAccountServiceUpdateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserAccountServiceUpdateArgs) SetReq(val *UpdateRequest) {
	p.Req = val
}

func (p *UserAccountServiceUpdateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserAccountServiceUpdateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceUpdateArgs(%+v)", *p)
}

var fieldIDToName_UserAccountServiceUpdateArgs = map[int16]string{
	1: "req",
}

type UserAccountServiceUpdateResult struct {
	Success *UpdateResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateResponse" json:"success,omitempty"`
}

func NewUserAccountServiceUpdateResult() *UserAccountServiceUpdateResult {
	return &UserAccountServiceUpdateResult{}
}

func (p *UserAccountServiceUpdateResult) InitDefault() {
}

var UserAccountServiceUpdateResult_Success_DEFAULT *UpdateResponse

func (p *UserAccountServiceUpdateResult) GetSuccess() (v *UpdateResponse) {
	if !p.IsSetSuccess() {
		return UserAccountServiceUpdateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserAccountServiceUpdateResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateResponse)
}

func (p *UserAccountServiceUpdateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserAccountServiceUpdateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountServiceUpdateResult(%+v)", *p)
}

var fieldIDToName_UserAccountServiceUpdateResult = map[int16]string{
	0: "success",
}
