// Code generated by Kitex v0.15.2. DO NOT EDIT.

package captchaservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	captcha "github.com/cloudwego_instance/rpc/verify_code/kitex_gen/captcha"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenerateCaptcha(ctx context.Context, req *captcha.GenerateCaptchaRequest, callOptions ...callopt.Option) (r *captcha.GenerateCaptchaResponse, err error)
	ValidateCaptcha(ctx context.Context, req *captcha.ValidateCaptchaRequest, callOptions ...callopt.Option) (r *captcha.ValidateCaptchaResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCaptchaServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCaptchaServiceClient struct {
	*kClient
}

func (p *kCaptchaServiceClient) GenerateCaptcha(ctx context.Context, req *captcha.GenerateCaptchaRequest, callOptions ...callopt.Option) (r *captcha.GenerateCaptchaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateCaptcha(ctx, req)
}

func (p *kCaptchaServiceClient) ValidateCaptcha(ctx context.Context, req *captcha.ValidateCaptchaRequest, callOptions ...callopt.Option) (r *captcha.ValidateCaptchaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ValidateCaptcha(ctx, req)
}
