// Code generated by Kitex v0.15.2. DO NOT EDIT.

package useraccountservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user_account "github.com/youperceive/cloudwego_instance/rpc/user_account/kitex_gen/user_account"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserAccountServiceRegisterArgs,
		newUserAccountServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserAccountServiceLoginArgs,
		newUserAccountServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userAccountServiceServiceInfo                = NewServiceInfo()
	userAccountServiceServiceInfoForClient       = NewServiceInfoForClient()
	userAccountServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userAccountServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userAccountServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userAccountServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserAccountService"
	handlerType := (*user_account.UserAccountService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user_account",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user_account.UserAccountServiceRegisterArgs)
	realResult := result.(*user_account.UserAccountServiceRegisterResult)
	success, err := handler.(user_account.UserAccountService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserAccountServiceRegisterArgs() interface{} {
	return user_account.NewUserAccountServiceRegisterArgs()
}

func newUserAccountServiceRegisterResult() interface{} {
	return user_account.NewUserAccountServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user_account.UserAccountServiceLoginArgs)
	realResult := result.(*user_account.UserAccountServiceLoginResult)
	success, err := handler.(user_account.UserAccountService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserAccountServiceLoginArgs() interface{} {
	return user_account.NewUserAccountServiceLoginArgs()
}

func newUserAccountServiceLoginResult() interface{} {
	return user_account.NewUserAccountServiceLoginResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user_account.RegisterRequest) (r *user_account.RegisterResponse, err error) {
	var _args user_account.UserAccountServiceRegisterArgs
	_args.Req = req
	var _result user_account.UserAccountServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user_account.LoginRequest) (r *user_account.LoginResponse, err error) {
	var _args user_account.UserAccountServiceLoginArgs
	_args.Req = req
	var _result user_account.UserAccountServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
