// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	order "github.com/youperceive/cloudwego_instance/api/biz/router/order"
	product "github.com/youperceive/cloudwego_instance/api/biz/router/product"
	user_account "github.com/youperceive/cloudwego_instance/api/biz/router/user_account"
	verify_code "github.com/youperceive/cloudwego_instance/api/biz/router/verify_code"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	product.Register(r)

	order.Register(r)

	user_account.Register(r)

	verify_code.Register(r)

}
