// Code generated by Kitex v0.15.2. DO NOT EDIT.

package captchaservice

import (
	captcha "CloudWeGoInstance/UserAccountService/kitex_gen/captcha"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenerateCaptcha": kitex.NewMethodInfo(
		generateCaptchaHandler,
		newCaptchaServiceGenerateCaptchaArgs,
		newCaptchaServiceGenerateCaptchaResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ValidateCaptcha": kitex.NewMethodInfo(
		validateCaptchaHandler,
		newCaptchaServiceValidateCaptchaArgs,
		newCaptchaServiceValidateCaptchaResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	captchaServiceServiceInfo                = NewServiceInfo()
	captchaServiceServiceInfoForClient       = NewServiceInfoForClient()
	captchaServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return captchaServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return captchaServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return captchaServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CaptchaService"
	handlerType := (*captcha.CaptchaService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "captcha",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func generateCaptchaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*captcha.CaptchaServiceGenerateCaptchaArgs)
	realResult := result.(*captcha.CaptchaServiceGenerateCaptchaResult)
	success, err := handler.(captcha.CaptchaService).GenerateCaptcha(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCaptchaServiceGenerateCaptchaArgs() interface{} {
	return captcha.NewCaptchaServiceGenerateCaptchaArgs()
}

func newCaptchaServiceGenerateCaptchaResult() interface{} {
	return captcha.NewCaptchaServiceGenerateCaptchaResult()
}

func validateCaptchaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*captcha.CaptchaServiceValidateCaptchaArgs)
	realResult := result.(*captcha.CaptchaServiceValidateCaptchaResult)
	success, err := handler.(captcha.CaptchaService).ValidateCaptcha(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCaptchaServiceValidateCaptchaArgs() interface{} {
	return captcha.NewCaptchaServiceValidateCaptchaArgs()
}

func newCaptchaServiceValidateCaptchaResult() interface{} {
	return captcha.NewCaptchaServiceValidateCaptchaResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenerateCaptcha(ctx context.Context, req *captcha.GenerateCaptchaRequest) (r *captcha.GenerateCaptchaResponse, err error) {
	var _args captcha.CaptchaServiceGenerateCaptchaArgs
	_args.Req = req
	var _result captcha.CaptchaServiceGenerateCaptchaResult
	if err = p.c.Call(ctx, "GenerateCaptcha", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ValidateCaptcha(ctx context.Context, req *captcha.ValidateCaptchaRequest) (r *captcha.ValidateCaptchaResponse, err error) {
	var _args captcha.CaptchaServiceValidateCaptchaArgs
	_args.Req = req
	var _result captcha.CaptchaServiceValidateCaptchaResult
	if err = p.c.Call(ctx, "ValidateCaptcha", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
