// Code generated by Kitex v0.15.2. DO NOT EDIT.
package verifycodeservice

import (
	server "github.com/cloudwego/kitex/server"
	verify_code "github.com/youperceive/cloudwego_instance/rpc/verify_code/kitex_gen/verify_code"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler verify_code.VerifyCodeService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler verify_code.VerifyCodeService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
