// Code generated by Kitex v0.15.2. DO NOT EDIT.

package orderservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	order "github.com/youperceive/cloudwego_instance/rpc/order/kitex_gen/order"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Create": kitex.NewMethodInfo(
		createHandler,
		newOrderServiceCreateArgs,
		newOrderServiceCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Update": kitex.NewMethodInfo(
		updateHandler,
		newOrderServiceUpdateArgs,
		newOrderServiceUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryOrderInfo": kitex.NewMethodInfo(
		queryOrderInfoHandler,
		newOrderServiceQueryOrderInfoArgs,
		newOrderServiceQueryOrderInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryOrderId": kitex.NewMethodInfo(
		queryOrderIdHandler,
		newOrderServiceQueryOrderIdArgs,
		newOrderServiceQueryOrderIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*order.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceCreateArgs)
	realResult := result.(*order.OrderServiceCreateResult)
	success, err := handler.(order.OrderService).Create(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCreateArgs() interface{} {
	return order.NewOrderServiceCreateArgs()
}

func newOrderServiceCreateResult() interface{} {
	return order.NewOrderServiceCreateResult()
}

func updateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceUpdateArgs)
	realResult := result.(*order.OrderServiceUpdateResult)
	success, err := handler.(order.OrderService).Update(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceUpdateArgs() interface{} {
	return order.NewOrderServiceUpdateArgs()
}

func newOrderServiceUpdateResult() interface{} {
	return order.NewOrderServiceUpdateResult()
}

func queryOrderInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceQueryOrderInfoArgs)
	realResult := result.(*order.OrderServiceQueryOrderInfoResult)
	success, err := handler.(order.OrderService).QueryOrderInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceQueryOrderInfoArgs() interface{} {
	return order.NewOrderServiceQueryOrderInfoArgs()
}

func newOrderServiceQueryOrderInfoResult() interface{} {
	return order.NewOrderServiceQueryOrderInfoResult()
}

func queryOrderIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceQueryOrderIdArgs)
	realResult := result.(*order.OrderServiceQueryOrderIdResult)
	success, err := handler.(order.OrderService).QueryOrderId(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceQueryOrderIdArgs() interface{} {
	return order.NewOrderServiceQueryOrderIdArgs()
}

func newOrderServiceQueryOrderIdResult() interface{} {
	return order.NewOrderServiceQueryOrderIdResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Create(ctx context.Context, req *order.CreateRequest) (r *order.CreateResponse, err error) {
	var _args order.OrderServiceCreateArgs
	_args.Req = req
	var _result order.OrderServiceCreateResult
	if err = p.c.Call(ctx, "Create", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Update(ctx context.Context, req *order.UpdateRequest) (r *order.UpdateResponse, err error) {
	var _args order.OrderServiceUpdateArgs
	_args.Req = req
	var _result order.OrderServiceUpdateResult
	if err = p.c.Call(ctx, "Update", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryOrderInfo(ctx context.Context, req *order.QueryOrderInfoRequest) (r *order.QueryOrderInfoResponse, err error) {
	var _args order.OrderServiceQueryOrderInfoArgs
	_args.Req = req
	var _result order.OrderServiceQueryOrderInfoResult
	if err = p.c.Call(ctx, "QueryOrderInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryOrderId(ctx context.Context, req *order.QueryOrderIdRequest) (r *order.QueryOrderIdResponse, err error) {
	var _args order.OrderServiceQueryOrderIdArgs
	_args.Req = req
	var _result order.OrderServiceQueryOrderIdResult
	if err = p.c.Call(ctx, "QueryOrderId", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
