// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Code int64

const (
	Code_SUCCESS       Code = 0
	Code_INVALID_PARAM Code = 1
	Code_DB_ERR        Code = 2
	Code_SERVICE_ERR   Code = 3
)

func (p Code) String() string {
	switch p {
	case Code_SUCCESS:
		return "SUCCESS"
	case Code_INVALID_PARAM:
		return "INVALID_PARAM"
	case Code_DB_ERR:
		return "DB_ERR"
	case Code_SERVICE_ERR:
		return "SERVICE_ERR"
	}
	return "<UNSET>"
}

func CodeFromString(s string) (Code, error) {
	switch s {
	case "SUCCESS":
		return Code_SUCCESS, nil
	case "INVALID_PARAM":
		return Code_INVALID_PARAM, nil
	case "DB_ERR":
		return Code_DB_ERR, nil
	case "SERVICE_ERR":
		return Code_SERVICE_ERR, nil
	}
	return Code(0), fmt.Errorf("not a valid Code string")
}

func CodePtr(v Code) *Code { return &v }
func (p *Code) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Code(result.Int64)
	return
}

func (p *Code) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TargetType int64

const (
	TargetType_Email TargetType = 1
	TargetType_Phone TargetType = 2
)

func (p TargetType) String() string {
	switch p {
	case TargetType_Email:
		return "Email"
	case TargetType_Phone:
		return "Phone"
	}
	return "<UNSET>"
}

func TargetTypeFromString(s string) (TargetType, error) {
	switch s {
	case "Email":
		return TargetType_Email, nil
	case "Phone":
		return TargetType_Phone, nil
	}
	return TargetType(0), fmt.Errorf("not a valid TargetType string")
}

func TargetTypePtr(v TargetType) *TargetType { return &v }
func (p *TargetType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TargetType(result.Int64)
	return
}

func (p *TargetType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BaseResponse struct {
	Code Code   `thrift:"code,1" frugal:"1,default,Code" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

func (p *BaseResponse) GetCode() (v Code) {
	return p.Code
}

func (p *BaseResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResponse) SetCode(val Code) {
	p.Code = val
}
func (p *BaseResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

var fieldIDToName_BaseResponse = map[int16]string{
	1: "code",
	2: "msg",
}
