// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package captcha

import (
	"context"
	"fmt"
	"github.com/youperceive/cloudwego_instance/rpc/verify_code/kitex_gen/base"
)

type GenerateCaptchaRequest struct {
	Type             base.TargetType `thrift:"type,1" frugal:"1,default,TargetType" json:"type"`
	Target           string          `thrift:"target,2" frugal:"2,default,string" json:"target"`
	Purpose          string          `thrift:"purpose,3" frugal:"3,default,string" json:"purpose"`
	ExpireSeconds    int32           `thrift:"expire_seconds,4,optional" frugal:"4,optional,i32" json:"expire_seconds,omitempty"`
	MaxValidateTimes int32           `thrift:"max_validate_times,5,optional" frugal:"5,optional,i32" json:"max_validate_times,omitempty"`
	Proj             string          `thrift:"proj,6" frugal:"6,default,string" json:"proj"`
	BizType          string          `thrift:"biz_type,7" frugal:"7,default,string" json:"biz_type"`
}

func NewGenerateCaptchaRequest() *GenerateCaptchaRequest {
	return &GenerateCaptchaRequest{
		ExpireSeconds:    300,
		MaxValidateTimes: 3,
	}
}

func (p *GenerateCaptchaRequest) InitDefault() {
	p.ExpireSeconds = 300
	p.MaxValidateTimes = 3
}

func (p *GenerateCaptchaRequest) GetType() (v base.TargetType) {
	return p.Type
}

func (p *GenerateCaptchaRequest) GetTarget() (v string) {
	return p.Target
}

func (p *GenerateCaptchaRequest) GetPurpose() (v string) {
	return p.Purpose
}

var GenerateCaptchaRequest_ExpireSeconds_DEFAULT int32 = 300

func (p *GenerateCaptchaRequest) GetExpireSeconds() (v int32) {
	if !p.IsSetExpireSeconds() {
		return GenerateCaptchaRequest_ExpireSeconds_DEFAULT
	}
	return p.ExpireSeconds
}

var GenerateCaptchaRequest_MaxValidateTimes_DEFAULT int32 = 3

func (p *GenerateCaptchaRequest) GetMaxValidateTimes() (v int32) {
	if !p.IsSetMaxValidateTimes() {
		return GenerateCaptchaRequest_MaxValidateTimes_DEFAULT
	}
	return p.MaxValidateTimes
}

func (p *GenerateCaptchaRequest) GetProj() (v string) {
	return p.Proj
}

func (p *GenerateCaptchaRequest) GetBizType() (v string) {
	return p.BizType
}
func (p *GenerateCaptchaRequest) SetType(val base.TargetType) {
	p.Type = val
}
func (p *GenerateCaptchaRequest) SetTarget(val string) {
	p.Target = val
}
func (p *GenerateCaptchaRequest) SetPurpose(val string) {
	p.Purpose = val
}
func (p *GenerateCaptchaRequest) SetExpireSeconds(val int32) {
	p.ExpireSeconds = val
}
func (p *GenerateCaptchaRequest) SetMaxValidateTimes(val int32) {
	p.MaxValidateTimes = val
}
func (p *GenerateCaptchaRequest) SetProj(val string) {
	p.Proj = val
}
func (p *GenerateCaptchaRequest) SetBizType(val string) {
	p.BizType = val
}

func (p *GenerateCaptchaRequest) IsSetExpireSeconds() bool {
	return p.ExpireSeconds != GenerateCaptchaRequest_ExpireSeconds_DEFAULT
}

func (p *GenerateCaptchaRequest) IsSetMaxValidateTimes() bool {
	return p.MaxValidateTimes != GenerateCaptchaRequest_MaxValidateTimes_DEFAULT
}

func (p *GenerateCaptchaRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GenerateCaptchaRequest(%+v)", *p)
}

var fieldIDToName_GenerateCaptchaRequest = map[int16]string{
	1: "type",
	2: "target",
	3: "purpose",
	4: "expire_seconds",
	5: "max_validate_times",
	6: "proj",
	7: "biz_type",
}

type GenerateCaptchaResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
}

func NewGenerateCaptchaResponse() *GenerateCaptchaResponse {
	return &GenerateCaptchaResponse{}
}

func (p *GenerateCaptchaResponse) InitDefault() {
}

var GenerateCaptchaResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GenerateCaptchaResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GenerateCaptchaResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GenerateCaptchaResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *GenerateCaptchaResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GenerateCaptchaResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GenerateCaptchaResponse(%+v)", *p)
}

var fieldIDToName_GenerateCaptchaResponse = map[int16]string{
	1: "baseResp",
}

type ValidateCaptchaRequest struct {
	Target  string `thrift:"target,1" frugal:"1,default,string" json:"target"`
	Purpose string `thrift:"purpose,2" frugal:"2,default,string" json:"purpose"`
	Captcha string `thrift:"captcha,3" frugal:"3,default,string" json:"captcha"`
	Proj    string `thrift:"proj,4" frugal:"4,default,string" json:"proj"`
	BizType string `thrift:"biz_type,5" frugal:"5,default,string" json:"biz_type"`
}

func NewValidateCaptchaRequest() *ValidateCaptchaRequest {
	return &ValidateCaptchaRequest{}
}

func (p *ValidateCaptchaRequest) InitDefault() {
}

func (p *ValidateCaptchaRequest) GetTarget() (v string) {
	return p.Target
}

func (p *ValidateCaptchaRequest) GetPurpose() (v string) {
	return p.Purpose
}

func (p *ValidateCaptchaRequest) GetCaptcha() (v string) {
	return p.Captcha
}

func (p *ValidateCaptchaRequest) GetProj() (v string) {
	return p.Proj
}

func (p *ValidateCaptchaRequest) GetBizType() (v string) {
	return p.BizType
}
func (p *ValidateCaptchaRequest) SetTarget(val string) {
	p.Target = val
}
func (p *ValidateCaptchaRequest) SetPurpose(val string) {
	p.Purpose = val
}
func (p *ValidateCaptchaRequest) SetCaptcha(val string) {
	p.Captcha = val
}
func (p *ValidateCaptchaRequest) SetProj(val string) {
	p.Proj = val
}
func (p *ValidateCaptchaRequest) SetBizType(val string) {
	p.BizType = val
}

func (p *ValidateCaptchaRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateCaptchaRequest(%+v)", *p)
}

var fieldIDToName_ValidateCaptchaRequest = map[int16]string{
	1: "target",
	2: "purpose",
	3: "captcha",
	4: "proj",
	5: "biz_type",
}

type ValidateCaptchaResponse struct {
	BaseResp *base.BaseResponse `thrift:"baseResp,1" frugal:"1,default,base.BaseResponse" json:"baseResp"`
	Valid    bool               `thrift:"valid,2" frugal:"2,default,bool" json:"valid"`
}

func NewValidateCaptchaResponse() *ValidateCaptchaResponse {
	return &ValidateCaptchaResponse{}
}

func (p *ValidateCaptchaResponse) InitDefault() {
}

var ValidateCaptchaResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *ValidateCaptchaResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return ValidateCaptchaResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ValidateCaptchaResponse) GetValid() (v bool) {
	return p.Valid
}
func (p *ValidateCaptchaResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *ValidateCaptchaResponse) SetValid(val bool) {
	p.Valid = val
}

func (p *ValidateCaptchaResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ValidateCaptchaResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateCaptchaResponse(%+v)", *p)
}

var fieldIDToName_ValidateCaptchaResponse = map[int16]string{
	1: "baseResp",
	2: "valid",
}

type CaptchaService interface {
	GenerateCaptcha(ctx context.Context, req *GenerateCaptchaRequest) (r *GenerateCaptchaResponse, err error)

	ValidateCaptcha(ctx context.Context, req *ValidateCaptchaRequest) (r *ValidateCaptchaResponse, err error)
}

type CaptchaServiceGenerateCaptchaArgs struct {
	Req *GenerateCaptchaRequest `thrift:"req,1" frugal:"1,default,GenerateCaptchaRequest" json:"req"`
}

func NewCaptchaServiceGenerateCaptchaArgs() *CaptchaServiceGenerateCaptchaArgs {
	return &CaptchaServiceGenerateCaptchaArgs{}
}

func (p *CaptchaServiceGenerateCaptchaArgs) InitDefault() {
}

var CaptchaServiceGenerateCaptchaArgs_Req_DEFAULT *GenerateCaptchaRequest

func (p *CaptchaServiceGenerateCaptchaArgs) GetReq() (v *GenerateCaptchaRequest) {
	if !p.IsSetReq() {
		return CaptchaServiceGenerateCaptchaArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CaptchaServiceGenerateCaptchaArgs) SetReq(val *GenerateCaptchaRequest) {
	p.Req = val
}

func (p *CaptchaServiceGenerateCaptchaArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CaptchaServiceGenerateCaptchaArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CaptchaServiceGenerateCaptchaArgs(%+v)", *p)
}

var fieldIDToName_CaptchaServiceGenerateCaptchaArgs = map[int16]string{
	1: "req",
}

type CaptchaServiceGenerateCaptchaResult struct {
	Success *GenerateCaptchaResponse `thrift:"success,0,optional" frugal:"0,optional,GenerateCaptchaResponse" json:"success,omitempty"`
}

func NewCaptchaServiceGenerateCaptchaResult() *CaptchaServiceGenerateCaptchaResult {
	return &CaptchaServiceGenerateCaptchaResult{}
}

func (p *CaptchaServiceGenerateCaptchaResult) InitDefault() {
}

var CaptchaServiceGenerateCaptchaResult_Success_DEFAULT *GenerateCaptchaResponse

func (p *CaptchaServiceGenerateCaptchaResult) GetSuccess() (v *GenerateCaptchaResponse) {
	if !p.IsSetSuccess() {
		return CaptchaServiceGenerateCaptchaResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CaptchaServiceGenerateCaptchaResult) SetSuccess(x interface{}) {
	p.Success = x.(*GenerateCaptchaResponse)
}

func (p *CaptchaServiceGenerateCaptchaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CaptchaServiceGenerateCaptchaResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CaptchaServiceGenerateCaptchaResult(%+v)", *p)
}

var fieldIDToName_CaptchaServiceGenerateCaptchaResult = map[int16]string{
	0: "success",
}

type CaptchaServiceValidateCaptchaArgs struct {
	Req *ValidateCaptchaRequest `thrift:"req,1" frugal:"1,default,ValidateCaptchaRequest" json:"req"`
}

func NewCaptchaServiceValidateCaptchaArgs() *CaptchaServiceValidateCaptchaArgs {
	return &CaptchaServiceValidateCaptchaArgs{}
}

func (p *CaptchaServiceValidateCaptchaArgs) InitDefault() {
}

var CaptchaServiceValidateCaptchaArgs_Req_DEFAULT *ValidateCaptchaRequest

func (p *CaptchaServiceValidateCaptchaArgs) GetReq() (v *ValidateCaptchaRequest) {
	if !p.IsSetReq() {
		return CaptchaServiceValidateCaptchaArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CaptchaServiceValidateCaptchaArgs) SetReq(val *ValidateCaptchaRequest) {
	p.Req = val
}

func (p *CaptchaServiceValidateCaptchaArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CaptchaServiceValidateCaptchaArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CaptchaServiceValidateCaptchaArgs(%+v)", *p)
}

var fieldIDToName_CaptchaServiceValidateCaptchaArgs = map[int16]string{
	1: "req",
}

type CaptchaServiceValidateCaptchaResult struct {
	Success *ValidateCaptchaResponse `thrift:"success,0,optional" frugal:"0,optional,ValidateCaptchaResponse" json:"success,omitempty"`
}

func NewCaptchaServiceValidateCaptchaResult() *CaptchaServiceValidateCaptchaResult {
	return &CaptchaServiceValidateCaptchaResult{}
}

func (p *CaptchaServiceValidateCaptchaResult) InitDefault() {
}

var CaptchaServiceValidateCaptchaResult_Success_DEFAULT *ValidateCaptchaResponse

func (p *CaptchaServiceValidateCaptchaResult) GetSuccess() (v *ValidateCaptchaResponse) {
	if !p.IsSetSuccess() {
		return CaptchaServiceValidateCaptchaResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CaptchaServiceValidateCaptchaResult) SetSuccess(x interface{}) {
	p.Success = x.(*ValidateCaptchaResponse)
}

func (p *CaptchaServiceValidateCaptchaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CaptchaServiceValidateCaptchaResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CaptchaServiceValidateCaptchaResult(%+v)", *p)
}

var fieldIDToName_CaptchaServiceValidateCaptchaResult = map[int16]string{
	0: "success",
}
