// Code generated by hertz generator.

package order

import (
	"context"
	"log"
	"os"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/client"
	"github.com/youperceive/cloudwego_instance/api/biz/middleware"
	"github.com/youperceive/cloudwego_instance/api/biz/model/base"
	order "github.com/youperceive/cloudwego_instance/api/biz/model/order"

	order_k "github.com/youperceive/cloudwego_instance/rpc/order/kitex_gen/order"
	order_service_k "github.com/youperceive/cloudwego_instance/rpc/order/kitex_gen/order/orderservice"
)

var orderServiceClient order_service_k.Client

func init() {
	cli, err := order_service_k.NewClient(
		"order_service",
		client.WithHostPorts(os.Getenv("order_service_addr")),
	)
	if err != nil {
		log.Fatal(err)
	}
	orderServiceClient = cli
}

// Create .
// @router /create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.CreateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	jwtUserID, exist := c.Get(middleware.UserIDKey)
	if !exist {
		c.JSON(consts.StatusInternalServerError, &order.CreateResponse{
			BaseResp: &base.BaseResponse{
				Code: base.Code_SERVICE_ERR,
				Msg:  "token.userId 不存在. Internal Error",
			},
		})
		return
	}
	userID, ok := jwtUserID.(int64)
	if !ok {
		c.JSON(consts.StatusInternalServerError, &order.CreateResponse{
			BaseResp: &base.BaseResponse{
				Code: base.Code_SERVICE_ERR,
				Msg:  "token.userId 解析失败. Internal Error",
			},
		})
		return
	}

	var items []*order_k.OrderItemForCreate
	for _, it := range req.Items {
		items = append(items, &order_k.OrderItemForCreate{
			ProductId: it.ProductID,
			SkuId:     it.SkuID,
			Count:     it.Count,
			Price:     it.Price,
			Ext:       it.Ext,
		})
	}

	reqK := &order_k.CreateRequest{
		Type:       req.Type,
		Status:     req.Status,
		ReqUserId:  userID,
		RespUserId: req.RespUserID,
		Items:      items,
		Ext:        req.Ext,
	}
	respK, err := orderServiceClient.Create(ctx, reqK)
	if err != nil {
		log.Println(err.Error())
		c.JSON(consts.StatusInternalServerError, &order.CreateResponse{
			BaseResp: &base.BaseResponse{
				Code: base.Code_SERVICE_ERR,
				Msg:  "Internal Error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &order.CreateResponse{
		BaseResp: &base.BaseResponse{
			Code: base.Code_SUCCESS,
			Msg:  "Success",
		},
		OrderID: respK.OrderId,
	})
}

// Update .
// @router /update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.UpdateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	reqK := &order_k.UpdateRequest{
		Id:     req.ID,
		Status: req.Status,
		Ext:    req.Ext,
	}
	respK, err := orderServiceClient.Update(ctx, reqK)
	if err != nil {
		log.Println(err.Error() + respK.String())
		c.JSON(consts.StatusInternalServerError, &order.UpdateResponse{
			BaseResp: &base.BaseResponse{
				Code: base.Code_SERVICE_ERR,
				Msg:  "Internal Error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &order.UpdateResponse{
		BaseResp: &base.BaseResponse{
			Code: base.Code_SUCCESS,
			Msg:  "Success",
		},
	})
}

// QueryOrderInfo .
// @router /query_order_info [POST]
func QueryOrderInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.QueryOrderInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	reqK := &order_k.QueryOrderInfoRequest{
		Id: req.ID,
	}
	respK, err := orderServiceClient.QueryOrderInfo(ctx, reqK)
	if err != nil {
		log.Println(err.Error() + respK.String())
		c.JSON(consts.StatusInternalServerError, &order.QueryOrderInfoResponse{
			BaseResp: &base.BaseResponse{
				Code: base.Code_SERVICE_ERR,
				Msg:  "Internal Error",
			},
		})
		return
	}

	var items []*order.OrderItem
	for _, it := range respK.Order.Items {
		items = append(items, &order.OrderItem{
			ProductID: it.ProductId,
			SkuID:     it.SkuId,
			Count:     it.Count,
			Price:     it.Price,
			Ext:       it.Ext,
		})
	}

	respOrder := order.Order{
		ID:         respK.Order.Id,
		Type:       respK.Order.Type,
		Status:     respK.Order.Status,
		ReqUserID:  respK.Order.ReqUserId,
		RespUserID: respK.Order.RespUserId,
		Items:      items,
		CreatedAt:  respK.Order.CreatedAt,
		UpdatedAt:  respK.Order.UpdatedAt,
		Ext:        respK.Order.Ext,
	}

	c.JSON(consts.StatusOK, &order.QueryOrderInfoResponse{
		BaseResp: &base.BaseResponse{
			Code: base.Code_SUCCESS,
			Msg:  "Success",
		},
		Order: &respOrder,
	})
}

// QueryOrderId .
// @router /query_order_id [POST]
func QueryOrderId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.QueryOrderIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	reqK := &order_k.QueryOrderIdRequest{
		Type:     order_k.QueryOrderIdType(req.Type),
		UserId:   req.UserID,
		ExtKey:   req.ExtKey,
		ExtVal:   req.ExtVal,
		Page:     req.Page,
		PageSize: req.PageSize,
	}
	respK, err := orderServiceClient.QueryOrderId(ctx, reqK)
	if err != nil {
		log.Println(err.Error() + respK.String())
		c.JSON(consts.StatusInternalServerError, &order.QueryOrderIdResponse{
			BaseResp: &base.BaseResponse{
				Code: base.Code_SERVICE_ERR,
				Msg:  "Internal Error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &order.QueryOrderIdResponse{
		BaseResp: &base.BaseResponse{
			Code: base.Code_SUCCESS,
			Msg:  "Success",
		},
		OrderID:  respK.OrderId,
		Total:    respK.Total,
		Page:     respK.Page,
		PageSize: respK.PageSize,
	})
}
